name: Triple G build and deploy

on:
  push:
    branches: ['develop']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -euo pipefail
            echo "Changing to deploy path"
            cd ${{ vars.STG_DEPLOY_PATH }}
            echo "Pulling latest code"
            git pull
            echo "Backing up database"
            drush sql:dump > /var/www/db_backups/${{ vars.STG_BU_FILE_PREFIX }}.$(date +'%Y-%m-%d_%H:%M:%S').sql
            echo "Installing composer dependencies"
            composer install
            echo "Installing npm dependencies"
            npm install
            echo "Building assets"
            npm run build
            echo "Cleaning up node_modules"
            rm -rf node_modules
            echo "Clearing Drupal cache"
            drush cr
            echo "Importing config"
            drush cim -y
            echo "Updating database"
            drush updb -y
            echo "Final cache clear"
            drush cr
            echo "Site deployed to staging"
