name: Run Lighthouse CI
permissions:
  contents: read

on:
  workflow_run:
    workflows:
      - "Triple G build and deploy"
    types:
      - completed

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Run Lighthouse CI
        uses: appleboy/ssh-action@v1
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -euo pipefail
            echo "Changing to deploy path"
            cd "${{ vars.STG_DEPLOY_PATH }}"
            echo "Running Lighthouse CI"
            lhci autorun --upload.github.appToken=$LHCI_GITHUB_APP_TOKEN
